import { StyleSheet } from 'react-native';

const menuModalStyles = StyleSheet.create({
  backContainer: {
    flex: 1,
    paddingTop: 50,
    backgroundColor: 'rgba(25,25,25,.75)',
  },
  container: {
    marginTop: 50,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
    flex: 1,
  },
  headerContainer: { display: 'flex', flexDirection: 'row' },
  headerImgContainer: {
    width: '60%',
    display: 'flex',
    alignItems: 'flex-end',
  },
  headerImg: {
    height: 75,
    width: 75,
    borderRadius: 50,
    marginTop: 25,
  },
  closeContainer: {
    width: '40%',
    display: 'flex',
    alignItems: 'flex-end',
  },
  closeIconContainer: {
    height: 40,
    width: 40,
    backgroundColor: '#F7F8F8',
    borderRadius: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  subTitle: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 50,
  },
});

const addModalStyles = StyleSheet.create({
  backContainer: {
    flex: 1,
    paddingTop: 50,
    backgroundColor: 'rgba(25,25,25,.75)',
  },
  container: {
    marginTop: 50,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
    flex: 1,
  },
  headerContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 45,
    width: '100%',
  },
  closeContainer: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'flex-end',
    top: 0,
    right: 0,
  },
  closeIconContainer: {
    height: 40,
    width: 40,
    backgroundColor: '#F7F8F8',
    borderRadius: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selected: {
    color: 'black',
  },
  unselected: {
    color: '#9A9FA7',
  },
  title: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  searchContainer: {
    width: '100%',
    height: 40,
    backgroundColor: '#F7F8F8',
    borderRadius: 50,
    marginTop: 15,
    padding: 5,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchIcon: { marginHorizontal: 5 },
  searchInput: { fontFamily: 'Metropolis-Regular', fontWeight: 'bold' },
  quickAddContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  quickAddText: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 20,
    fontWeight: 'bold',
  },
  quickAddTextUnselected: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 20,
    fontWeight: 'bold',
    color: 'red',
  },
  allContactsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '40%',
  },
  allContactsText: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 16,
    color: '#9A9FA7',
    fontWeight: 'bold',
  },
  allContactsTextBold: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 16,
    color: 'black',
    fontWeight: 'bold',
  },
  friendsTitle: {
    fontFamily: 'Metropolis-Regular',
    fontWeight: 'bold',
    fontSize: 22,
  },
  scrollContainer: { width: '100%' },
  chatButton: {
    position: 'absolute',
    width: '65%',
    paddingVertical: 10,
    borderRadius: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 45,
    backgroundColor: '#0EADFF',
  },
  chatButtonDisabled: {
    backgroundColor: '#B9C0C6',
    position: 'absolute',
    width: '65%',
    paddingVertical: 10,
    borderRadius: 50,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 45,
  },
  chatTitle: {
    fontFamily: 'Metropolis-Regular',
    fontSize: 28,
    color: '#FFF',
    fontWeight: 'bold',
  },
});

const addContactRowStyles = StyleSheet.create({
  container: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    // backgroundColor: 'red',
    margin: 2,
  },
  imgContainer: {
    width: '20%',
    // backgroundColor: 'red',
    alignSelf: 'center',
  },
  img: { width: 50, height: 50, borderRadius: 50 },
  titlesContainer: {
    width: '55%',
    display: 'flex',
    justifyContent: 'center',
  },
  title: { fontFamily: 'Metropolis-Regular', fontWeight: 'bold', fontSize: 24 },
  subTitle: {
    fontFamily: 'Metropolis-Regular',
    color: '#9A9FA7',
    fontWeight: 'bold',
  },
  iconContainer: {
    width: '25%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  pendingContainer: {
    display: 'flex',
    width: '25%',
    height: 30,
    backgroundColor: '#0EADFF',
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  pendingTitle: {
    fontFamily: 'Metropolis-Regular',
    color: '#FFF',
    fontWeight: 'bold',
  },
  selectChatContainer: {
    display: 'flex',
    width: '22.5%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  selectChat: {
    height: 30,
    width: 30,
    borderWidth: 2,
    borderRadius: 50,
    borderColor: '#F7F8F8',
  },
  chatSelected: {
    height: 30,
    width: 30,
    backgroundColor: '#0EADFF',
    borderRadius: 50,
    borderColor: '#F7F8F8',
    borderWidth: 2,
  },
  shadowImage: {
    // backgroundColor: 'red',
    padding: 3,
    // borderRadius:100,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
});

const chatModalStyles = StyleSheet.create({
  container: {
    marginTop: 150,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
    flex: 1,
  },
});

export {
  menuModalStyles,
  addModalStyles,
  addContactRowStyles,
  chatModalStyles,
};
