export const types = {
  RegisterName: '[Register] Set Name',
  RegisterBirthday: '[Register] Set Birthday',
  RegisterPhone: '[Register] Set Phone',
  RegisterEmail: '[Register] Set Email',
  RegisterUsername: '[Register] Set Username',
  RegisterPassword: '[Register] Set Password',
  RegisterPhoto: '[Register] Set Photo',
  RegisterError: '[Register] Set Error',

  SessionAuthenticate: '[Session] Authenticate User',
  SessionLogout: '[Session] Logout User',
  SessionEditProfile: '[Session] Edit Profile',
  SessionOpenMenu: '[Session] Open Menu',
  SessionCloseMenu: '[Session] Close Menu',
  SessionOpenAddFriend: '[Session] Open Add Friend',
  SessionCloseAddFriend: '[Session] Close Add Friend',
  SessionOpenAddChat: '[Session] Open Add Chat',
  SessionCloseAddChat: '[Session] Close Add Chat',
  SessionOpenGroup: '[Session] Open Group',
  SessionCloseGroup: '[Session] Close Group',
  SessionOpenProfile: '[Session] Open Profile',
  SessionCloseProfile: '[Session] Close Profile',
  SessionOpenShareUser: '[Session] Open Share User',
  SessionCloseShareUser: '[Session] Close Share User',
  SessionOpenContacts: '[Session] Open Contacts',
  SessionDeleteContact: '[Session] Delete Contacts',
  SessionOpenFriendRequests: '[Session] Open Friends Requests',
  SessionDeleteFriendRequest: '[Session] Delete Friend Request',
  SessionOpenFollowersRequests: '[Session] Open Followers Requests',
  SessionDeleteFollowerRequest: '[Session] Delete Follower Request',
};
